# config/global_costmap_params.yaml
# ATENCAO: REMOVIDA a chave "global_costmap:" do topo

global_frame: map
robot_base_frame: base_link
update_interval: 5.0
static_map: true
rolling_window: false
transform_tolerance: 5.0 # <--- Agora sera lido

plugins:
  - {name: static_layer,    type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

obstacle_layer:
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {
    sensor_frame: base_laser,
    data_type: LaserScan,
    topic: /scan,
    marking: true,
    clearing: true
  }
