# config/local_costmap_params.yaml
# ATENCAO: REMOVIDA a chave "local_costmap:" do topo

global_frame: odom
robot_base_frame: base_link
update_interval: 1.0
publish_frequency: 5.0
static_map: false
rolling_window: true
transform_tolerance: 5.0 # <--- Agora sera lido
width: 1.5
height: 1.5
resolution: 0.05

plugins:
  - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

obstacle_layer:
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {
    sensor_frame: base_laser,
    data_type: LaserScan,
    topic: /scan,
    marking: true,
    clearing: true
  }
